# secrets.toml
AZURE_OPENAI_KEY = "735b77ae2ab344e4b23d7f3e3f256ca9"
AZURE_OPENAI_ENDPOINT = "https://basee-m2hc7i7r-australiaeast.openai.azure.com"
TEXT_ANALYTICS_KEY = "38b0851c949e4743bcc696ade25b26c0"
TEXT_ANALYTICS_ENDPOINT = "https://convundr.cognitiveservices.azure.com"
CONVERSATION_ANALYSIS_API_KEY = "38b0851c949e4743bcc696ade25b26c0"
CONVERSATION_ANALYSIS_ENDPOINT = "https://convundr.cognitiveservices.azure.com/"
AI_SERVICE_ENDPOINT = "https://ocrth.cognitiveservices.azure.com/"
AI_SERVICE_KEY = "288f47800ce24f468f20a832a62d50db"
Hugging_Face = "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"
AZURE_API_KEY = "9e87d2057053451883dd5f5a8bbfb5ac"
AZURE_ENDPOINT = "https://documintl.cognitiveservices.azure.com/"
